// Top-level build file for XRC Rat
// Target: Android 15 (API 35) | Min: Android 7.0 (API 24)
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
